/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_m_java_2;

import javax.swing.JFrame;

/**
 *
 * @author Nikolas
 */
public class Einstellungen extends javax.swing.JFrame {

    JFrame jfrm_Menu;
    /**
     * Creates new form Einstellungen
     */
    public Einstellungen(JFrame Menu) {
        jfrm_Menu = Menu;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_anz_spieler = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jlbl_anz_spieler = new javax.swing.JLabel();
        jlbl_spieler1 = new javax.swing.JLabel();
        jlbl_spieler2 = new javax.swing.JLabel();
        jlbl_spieler3 = new javax.swing.JLabel();
        jlbl_spieler4 = new javax.swing.JLabel();
        tf_spielername_red = new javax.swing.JTextField();
        tf_spielername_green = new javax.swing.JTextField();
        tf_spielername_yellow = new javax.swing.JTextField();
        tf_spielername_blue = new javax.swing.JTextField();
        jcb_cpu_red = new javax.swing.JCheckBox();
        jcb_spu_green = new javax.swing.JCheckBox();
        jcb_cpu_yellow = new javax.swing.JCheckBox();
        jcb_cpu_blue = new javax.swing.JCheckBox();
        jbtn_zurueck = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg_anz_spieler.add(jRadioButton1);
        jRadioButton1.setText("2");

        bg_anz_spieler.add(jRadioButton2);
        jRadioButton2.setText("3");
        jRadioButton2.setActionCommand("3");

        bg_anz_spieler.add(jRadioButton3);
        jRadioButton3.setSelected(true);
        jRadioButton3.setText("4");

        jlbl_anz_spieler.setText("Anzahl Spieler");

        jlbl_spieler1.setText("Spieler 1");

        jlbl_spieler2.setText("Spieler 2");

        jlbl_spieler3.setText("Spieler 3");

        jlbl_spieler4.setText("Spieler 4");

        tf_spielername_red.setText("Red");

        tf_spielername_green.setText("Green");

        tf_spielername_yellow.setText("Yellow");

        tf_spielername_blue.setText("Green");

        jcb_cpu_red.setText("CPU");

        jcb_spu_green.setText("CPU");

        jcb_cpu_yellow.setText("CPU");

        jcb_cpu_blue.setText("CPU");

        jbtn_zurueck.setText("Zurück zum Menü");
        jbtn_zurueck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_zurueckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlbl_spieler2)
                            .addComponent(jlbl_spieler1)
                            .addComponent(jlbl_spieler3)
                            .addComponent(jlbl_spieler4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tf_spielername_red, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jcb_cpu_red))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tf_spielername_green, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(jcb_spu_green))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_spielername_yellow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_spielername_blue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcb_cpu_blue)
                                    .addComponent(jcb_cpu_yellow)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbl_anz_spieler)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton3)))
                .addContainerGap(190, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtn_zurueck)
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jlbl_anz_spieler))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_spieler1)
                    .addComponent(tf_spielername_red, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_cpu_red))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_spieler2)
                    .addComponent(tf_spielername_green, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_spu_green))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_spieler3)
                    .addComponent(tf_spielername_yellow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_cpu_yellow))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_spieler4)
                    .addComponent(tf_spielername_blue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_cpu_blue))
                .addGap(46, 46, 46)
                .addComponent(jbtn_zurueck)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_zurueckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_zurueckActionPerformed
        // TODO add your handling code here:
        jfrm_Menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtn_zurueckActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_anz_spieler;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JButton jbtn_zurueck;
    private javax.swing.JCheckBox jcb_cpu_blue;
    private javax.swing.JCheckBox jcb_cpu_red;
    private javax.swing.JCheckBox jcb_cpu_yellow;
    private javax.swing.JCheckBox jcb_spu_green;
    private javax.swing.JLabel jlbl_anz_spieler;
    private javax.swing.JLabel jlbl_spieler1;
    private javax.swing.JLabel jlbl_spieler2;
    private javax.swing.JLabel jlbl_spieler3;
    private javax.swing.JLabel jlbl_spieler4;
    private javax.swing.JTextField tf_spielername_blue;
    private javax.swing.JTextField tf_spielername_green;
    private javax.swing.JTextField tf_spielername_red;
    private javax.swing.JTextField tf_spielername_yellow;
    // End of variables declaration//GEN-END:variables
}
